#install script
#Author - Sumant Murke

- hosts: all
  sudo: True
  roles:
    - { role: JasonGiedymin.java, java_version: "7", tags:['runtimes']}
    - { role: sumantmurke.zookeeper, zookeeper_version: "3.4.6"}

